# Pretraining on one dataset and then train on another

## Train baseline

### Prepare PAMAP2 dataset

In [1]:
from cnn1d_modules import Model, Dataset
from statistics import Statistics
dataset_obj = Dataset("pa2")
dataset_obj.read_dataset()
dataset_obj.downsample_dataset()
dataset_obj.segment_dataset()

Instructions for updating:
non-resource variables are not supported in the long term
PATH:  /home/dmitrii/GitHub/SDAPraktikum/E3/PAMAP2_Dataset/pamap2.h5
x_train shape =  (128247, 52)
y_train shape = (128247,)
x_test shape = (22659, 52)
y_test shape = (22659,)
x_train shape(downsampled) =  (42749, 52)
y_train shape(downsampled) = (42749,)
x_test shape(downsampled) = (7553, 52)
y_test shape(downsampled) = (7553,)
[ 1  2  3  4  5  6  7 11 12 13 14 18]
[ 1  2  3  4  5  6  7 11 12 13 14 18]
segmenting signal...
signal segmented.
train_x shape = (3561, 25, 52)
train_y shape = (3561,)
test_x shape = (628, 25, 52)
test_y shape = (628,)


(array([[[ 0.001     ,  0.1       ,  0.030375  , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.1       ,  0.030375  , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.101     ,  0.030375  , ...,  0.001     ,
           0.        ,  0.        ],
         ...,
         [ 0.001     ,  0.102     ,  0.0305    , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.102     ,  0.0305    , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.102     ,  0.0305    , ...,  0.001     ,
           0.        ,  0.        ]],
 
        [[ 0.001     ,  0.102     ,  0.0304375 , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.102     ,  0.0304375 , ...,  0.001     ,
           0.        ,  0.        ],
         [ 0.001     ,  0.102     ,  0.0304375 , ...,  0.001     ,
           0.        ,  0.        ],
         ...,
         [ 0.001     ,  0.103    

Train model numerous times to get mean and standard deviation

In [2]:
model = Model(dataset_obj)
stats = Statistics()
num_experiments = 5

for i in range(num_experiments):
    model.build_model(load_weights=False)
    model.run_model(training_epochs=50)
    test_accuracy, val_accuracy, y_pred, y_true = model.test()
    stats.add(test_accuracy, val_accuracy, y_pred, y_true)

pa2
X shape = (?, 1, 25, 52)
Y shape = (?, 11)
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
hidden layer 1 shape
W_conv1 shape = (1, 7, 52, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 19, 128)
h_pool1 shape = (?, 1, 7, 128)
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 5, 128)
h_pool2 shape = (?, 1, 2, 128)
shape's shape: [None, 1, 2, 128]
c_flat shape = (?, 256)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0 0 0 0 0 0 0 0 0 0]
train_y shape(1-hot) = (3561, 11)
test_y shape(1-hot) = (628, 11)
train_x_reshaped =  (3561, 1, 25, 52)
test_x_reshaped =  (628, 1, 25, 52)
train_x shape = (3561, 25, 52)
train_y shape = (3561,)
test_x shape = (628, 25, 52)
test_y shape = (628,)
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_log

2022-07-10 10:28:37.276207: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-07-10 10:28:37.276513: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-10 10:28:37.281219: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-07-10 10:28:37.291935: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2022-07-10 10:28:37.320873: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 1796665000 Hz


Epoch:  0  Training Loss:  2.5160903453826906  Training Accuracy:  0.22128616
Epoch:  1  Training Loss:  2.1487642483277756  Training Accuracy:  0.33951136
Epoch:  2  Training Loss:  1.937484627420252  Training Accuracy:  0.38107273
Epoch:  3  Training Loss:  1.7567375047640368  Training Accuracy:  0.42768884
Epoch:  4  Training Loss:  1.6106655836105346  Training Accuracy:  0.47598988
Epoch:  5  Training Loss:  1.474823589216579  Training Accuracy:  0.5321539
Epoch:  6  Training Loss:  1.3379659966988997  Training Accuracy:  0.57371527
Epoch:  7  Training Loss:  1.2419505579905077  Training Accuracy:  0.61022186
Epoch:  8  Training Loss:  1.1575684793970802  Training Accuracy:  0.641112
Epoch:  9  Training Loss:  1.068313478068872  Training Accuracy:  0.6602078
Epoch:  10  Training Loss:  1.011817881464958  Training Accuracy:  0.6807077
Epoch:  11  Training Loss:  0.94813705005429  Training Accuracy:  0.70205
Epoch:  12  Training Loss:  0.8857863152568991  Training Accuracy:  0.711878

In [3]:
stats.show()

Test accuracy. Mean (std) = 0.724 (0.035)
Val accuracy. Mean (std) = 0.724 (0.035)
f1 score weighted. Mean (std) = 0.683 (0.046)
f1 score mean. Mean (std) = 0.680 (0.044)


## Pretrain the model on Opportunity dataset

In [4]:
dataset_obj2 = Dataset("opp")
dataset_obj2.read_dataset()
dataset_obj2.downsample_dataset()
dataset_obj2.segment_dataset()
model2 = Model(dataset_obj2)
model2.build_model(load_weights=False)
model2.run_model(training_epochs=50)

PATH:  /home/dmitrii/GitHub/SDAPraktikum/E3/OpportunityUCIDataset/opportunity.h5
x_train shape =  (700165, 77)
y_train shape = (700165,)
x_test shape = (120516, 77)
y_test shape = (120516,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
segmenting signal...
signal segmented.
train_x shape = (63650, 23, 77)
train_y shape = (63650,)
test_x shape = (10955, 23, 77)
test_y shape = (10955,)
opp
X shape = (?, 1, 23, 77)
Y shape = (?, 18)
hidden layer 1 shape
W_conv1 shape = (1, 7, 77, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 17, 128)
h_pool1 shape = (?, 1, 6, 128)
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 4, 128)
h_pool2 shape = (?, 1, 1, 128)
shape's shape: [None, 1, 1, 128]
c_flat shape = (?, 128)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
train_y shape(1-hot) = (63650, 18)
test_y shape(1-hot) = (10955, 18)
train_

In [5]:
model2.test()

INFO:tensorflow:Restoring parameters from opp
Testing Accuracy: 0.9002282
validation accuracy: 0.9002282


(0.9002282,
 0.9002282,
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]))

## Train the model again but with pretrained hidden layer
The network consists of input layer, hidden layer and output layer.
Since only hidden layer is common for all datasets, we replace only this.


In [8]:
stats2 = Statistics()
for i in range(num_experiments):
    model.W_conv2_weight = model2.W_conv2_weight
    model.b_conv2_weight = model2.b_conv2_weight
    model.build_model(load_weights=True)
    model.run_model(training_epochs=50)
    test_accuracy, val_accuracy, y_pred, y_true = model.test()
    stats2.add(test_accuracy, val_accuracy, y_pred, y_true)

pa2
X shape = (?, 1, 25, 52)
Y shape = (?, 11)
hidden layer 1 shape
W_conv1 shape = (1, 7, 52, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 19, 128)
h_pool1 shape = (?, 1, 7, 128)
WEIGHTS ARE LOADED
WEIGHTS ARE LOADED
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 5, 128)
h_pool2 shape = (?, 1, 2, 128)
shape's shape: [None, 1, 2, 128]
c_flat shape = (?, 256)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0 0 0 0 0 0 0 0 0 0]
train_y shape(1-hot) = (3561, 11)
test_y shape(1-hot) = (628, 11)
train_x_reshaped =  (3561, 1, 25, 52)
test_x_reshaped =  (628, 1, 25, 52)
train_x shape = (3561, 25, 52)
train_y shape = (3561,)
test_x shape = (628, 25, 52)
test_y shape = (628,)
Epoch:  0  Training Loss:  2.346703381971879  Training Accuracy:  0.19095759
Epoch:  1  Training Loss:  2.1785026387734847  Training Accuracy:  0.21903959
Epoch:  2  Training Loss:  2.076294479586861  Training Accuracy:  0.23336141
Epoch:  3  Training Loss: 

In [9]:
stats2.show()

Test accuracy. Mean (std) = 0.811 (0.069)
Val accuracy. Mean (std) = 0.811 (0.069)
f1 score weighted. Mean (std) = 0.802 (0.073)
f1 score mean. Mean (std) = 0.774 (0.085)
