# Pretraining on one dataset and then train on another

## Train baseline

### Prepare Daphnet dataset

In [2]:
from cnn1d_modules import Model, Dataset
from statistics import Statistics
dataset_obj = Dataset("dap")
dataset_obj.read_dataset()
dataset_obj.downsample_dataset()
dataset_obj.segment_dataset()

PATH:  C:\Users\olaei\OneDrive\Documents\Uni\Master\PSDA\Uebung3\Deep-Learning-for-Human-Activity-Recognition\Datareader\daphnet.h5
x_train shape =  (938908, 9)
y_train shape = (938908,)
x_test shape = (90562, 9)
y_test shape = (90562,)
x_train shape(downsampled) =  (469454, 9)
y_train shape(downsampled) = (469454,)
x_test shape(downsampled) = (45281, 9)
y_test shape(downsampled) = (45281,)
[1 2]
[1 2]
dap seg
segmenting signal...
signal segmented.
train_x shape = (39120, 25, 9)
train_y shape = (39120,)
test_x shape = (3772, 25, 9)
test_y shape = (3772,)


(array([[[-0.03 ,  0.99 ,  0.326, ..., -0.038,  1.   ,  0.029],
         [-0.02 ,  0.99 ,  0.336, ..., -0.038,  1.038,  0.009],
         [ 0.   ,  0.99 ,  0.316, ..., -0.029,  1.038,  0.029],
         ...,
         [-0.05 ,  0.99 ,  0.326, ..., -0.048,  1.009,  0.019],
         [-0.04 ,  0.98 ,  0.316, ..., -0.019,  1.009, -0.019],
         [-0.03 ,  0.98 ,  0.326, ...,  0.   ,  1.047, -0.029]],
 
        [[ 0.07 ,  1.009,  0.306, ...,  0.019,  1.009,  0.038],
         [-0.07 ,  1.019,  0.287, ...,  0.029,  1.   ,  0.009],
         [-0.111,  0.99 ,  0.297, ...,  0.   ,  1.028,  0.   ],
         ...,
         [-0.08 ,  1.019,  0.306, ...,  0.   ,  1.009, -0.019],
         [-0.05 ,  0.98 ,  0.346, ..., -0.038,  1.019, -0.009],
         [-0.05 ,  0.98 ,  0.326, ..., -0.048,  1.038, -0.009]],
 
        [[-0.03 ,  0.98 ,  0.326, ...,  0.   ,  1.047, -0.029],
         [-0.02 ,  0.99 ,  0.356, ..., -0.009,  1.047,  0.009],
         [-0.06 ,  0.99 ,  0.306, ...,  0.019,  1.038,  0.009],
      

Train model numerous times to get mean and standard deviation

In [3]:
model = Model(dataset_obj)
stats = Statistics()
num_experiments = 5

for i in range(num_experiments):
    model.build_model(load_weights=False)
    model.run_model(training_epochs=50)
    test_accuracy, val_accuracy, y_pred, y_true = model.test()
    stats.add(test_accuracy, val_accuracy, y_pred, y_true)

dap
X shape = (?, 1, 25, 9)
Y shape = (?, 2)
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
hidden layer 1 shape
W_conv1 shape = (1, 7, 9, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 19, 128)
h_pool1 shape = (?, 1, 7, 128)
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 5, 128)
h_pool2 shape = (?, 1, 2, 128)
shape's shape: [None, 1, 2, 128]
c_flat shape = (?, 256)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0]
train_y shape(1-hot) = (39120, 2)
test_y shape(1-hot) = (3772, 2)
train_x_reshaped =  (39120, 1, 25, 9)
test_x_reshaped =  (3772, 1, 25, 9)
train_x shape = (39120, 25, 9)
train_y shape = (39120,)
test_x shape = (3772, 25, 9)
test_y shape = (3772,)
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Instructi

In [4]:
stats.show()

Test accuracy. Mean (std) = 0.910 (0.005)
Val accuracy. Mean (std) = 0.910 (0.005)
f1 score weighted. Mean (std) = 0.902 (0.008)
f1 score mean. Mean (std) = 0.764 (0.024)


## Pretrain the model on Opportunity dataset

In [5]:
dataset_obj2 = Dataset("opp")
dataset_obj2.read_dataset()
dataset_obj2.downsample_dataset()
dataset_obj2.segment_dataset()
model2 = Model(dataset_obj2)
model2.build_model(load_weights=False)
model2.run_model(training_epochs=50)

PATH:  C:\Users\olaei\OneDrive\Documents\Uni\Master\PSDA\Uebung3\Deep-Learning-for-Human-Activity-Recognition\Datareader\opportunity.h5
x_train shape =  (700165, 77)
y_train shape = (700165,)
x_test shape = (120516, 77)
y_test shape = (120516,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
segmenting signal...
signal segmented.
train_x shape = (63650, 23, 77)
train_y shape = (63650,)
test_x shape = (10955, 23, 77)
test_y shape = (10955,)
opp
X shape = (?, 1, 23, 77)
Y shape = (?, 18)
hidden layer 1 shape
W_conv1 shape = (1, 7, 77, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 17, 128)
h_pool1 shape = (?, 1, 6, 128)
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 4, 128)
h_pool2 shape = (?, 1, 1, 128)
shape's shape: [None, 1, 1, 128]
c_flat shape = (?, 128)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
train_y shape(1-hot)

In [6]:
model2.test()

INFO:tensorflow:Restoring parameters from opp
Testing Accuracy: 0.8953902
validation accuracy: 0.8953902


(0.8953902,
 0.8953902,
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

## Train the model again but with pretrained hidden layer
The network consists of input layer, hidden layer and output layer.
Since only hidden layer is common for all datasets, we replace only this.


In [7]:
stats2 = Statistics()
for i in range(num_experiments):
    model.W_conv2_weight = model2.W_conv2_weight
    model.b_conv2_weight = model2.b_conv2_weight
    model.build_model(load_weights=True)
    model.run_model(training_epochs=50)
    test_accuracy, val_accuracy, y_pred, y_true = model.test()
    stats2.add(test_accuracy, val_accuracy, y_pred, y_true)

dap
X shape = (?, 1, 25, 9)
Y shape = (?, 2)
hidden layer 1 shape
W_conv1 shape = (1, 7, 9, 128)
b_conv1 shape = (128,)
h_conv1 shape = (?, 1, 19, 128)
h_pool1 shape = (?, 1, 7, 128)
WEIGHTS ARE LOADED
WEIGHTS ARE LOADED
hidden layer 2 shape
W_conv2 shape = (1, 3, 128, 128)
b_conv2 shape = (128,)
h_conv2 shape = (?, 1, 5, 128)
h_pool2 shape = (?, 1, 2, 128)
shape's shape: [None, 1, 2, 128]
c_flat shape = (?, 256)
unique test_y [0 1]
unique train_y [0 1]
test_y[1]= [1 0]
train_y shape(1-hot) = (39120, 2)
test_y shape(1-hot) = (3772, 2)
train_x_reshaped =  (39120, 1, 25, 9)
test_x_reshaped =  (3772, 1, 25, 9)
train_x shape = (39120, 25, 9)
train_y shape = (39120,)
test_x shape = (3772, 25, 9)
test_y shape = (3772,)
Epoch:  0  Training Loss:  0.30075499762419144  Training Accuracy:  0.91301125
Epoch:  1  Training Loss:  0.26148885024414187  Training Accuracy:  0.91301125
Epoch:  2  Training Loss:  0.23503219977498394  Training Accuracy:  0.9129857
Epoch:  3  Training Loss:  0.229354144191

In [8]:
stats2.show()

Test accuracy. Mean (std) = 0.901 (0.003)
Val accuracy. Mean (std) = 0.901 (0.003)
f1 score weighted. Mean (std) = 0.893 (0.003)
f1 score mean. Mean (std) = 0.744 (0.010)


Pre-training on the oppurtunity data set and using the resulting weights on the daphnet data set deliver worse F1-score.